


# This is a basic workflow to help you get started with Actions

name: Docker-Lint (Hado)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Hadolint Action
        # You may pin to the exact commit or the version.
        # uses: hadolint/hadolint-action@c27bd9edc1e95eed30474db8f295ff5807ebca14
        uses: hadolint/hadolint-action@v1.5.0
        with:
          # The path to the Dockerfile to lint
          dockerfile: Dockerfile# optional, default is Dockerfile
          # The output format, one of [tty (default) | json | checkstyle |codeclimate | gitlab_codeclimate ]

          format: # optional, default is tty
          # Fail the pipeline only if rules with severity above this threshold are violated. One of [error | warning | info (default) | style | ignore]

          failure-threshold: info # optional, default is info
          # A space separated string of rules to ignore
          ignore: # optional
          # Path to a config file
          config: # optional
