on:
  push:
    branches:
      - main

name: Write to Slack
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          channel-id: 'C029UCWE8A2'  # Slack channel id to post message
          slack-message: | 
             Vulnerabilities: https://github.com/TirthParikh27/AddSEC-demo/security/code-scanning
             Solution: https:://hello.com
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
